name: FleetSec DevSecOps Pipeline

on:
  push:
    branches:
      - "feature/**"

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  build-test-sbom:
    name: Build, Test and SBOM
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Execute tests
        run: npm test

      - name: Generate CycloneDX SBOM
        run: npm run sbom

      - name: Validate SBOM JSON
        run: jq empty ../reports/sbom/bom.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: cyclonedx-sbom
          path: reports/sbom/bom.json
          retention-days: 7
          if-no-files-found: error

  secrets-gitleaks:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout complete Git history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scan repository for secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  semgrep:
    name: Semgrep SAST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: pipx install semgrep

      - name: Run SQL Injection rule
        run: |
          semgrep scan \
  --config app/.semgrep/fleetsec-sqli.yml \
  app/src
      - name: Run Sensitive Logging rule
        run: |
            semgrep scan \
  --config app/.semgrep/fleetsec-sensitive-logging.yml \
  app/tests/semgrep
  checkov:
    name: Checkov IaC Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform
          config_file: .checkov/config.yaml
          framework: terraform
          quiet: true
  trivy:
    name: Trivy Vulnerability Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: app
          format: sarif
          output: trivy-results.sarif

      - name: Upload Trivy SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
